import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatIconModule,
  MatInputModule,
  MatSnackBarModule,
  MatListModule,
  MatNativeDateModule,
  MatSidenavModule,
  MatSortModule,
  MatToolbarModule,
  MatTabsModule,
  MatDividerModule,
  MatStepperModule,
  MatPaginatorModule,
  MatMenuModule,
  MatDialogModule,
  MatExpansionModule,
  MatSlideToggleModule,
  MatSelectModule,
  MatDatepickerModule,
  MatProgressSpinnerModule,
  MatGridListModule,
  MatTableModule,
  MatChipsModule,
  MatRadioModule,
  MatCheckboxModule
} from '@angular/material';
import { NgxMaterialTimepickerModule } from 'ngx-material-timepicker';

@NgModule({
  declarations: [],
  imports: [
    NgxMaterialTimepickerModule,
    CommonModule,
    MatCardModule,
    MatPaginatorModule,
    MatDividerModule,
    MatChipsModule,
    MatDialogModule,
    MatExpansionModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatRadioModule,
    MatStepperModule,
    MatDatepickerModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatTabsModule,
    MatNativeDateModule,
    MatGridListModule,
    MatMenuModule,
    MatTableModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatSortModule,
    MatCheckboxModule,
    MatSnackBarModule
  ],
  exports: [
    NgxMaterialTimepickerModule,
    CommonModule,
    MatDividerModule,
    MatCardModule,
    MatRadioModule,
    MatCheckboxModule,
    MatPaginatorModule,
    MatChipsModule,
    MatDialogModule,
    MatExpansionModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatStepperModule,
    MatDatepickerModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatNativeDateModule,
    MatGridListModule,
    MatMenuModule,
    MatTabsModule,
    MatTableModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatSortModule,
    MatSnackBarModule
  ]
})
export class MaterialModule { }
